---
# tasks file for setup_bind

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Set timezone to Asia/Riyadh
  community.general.timezone:
    name: Asia/Riyadh

- name: Change ownership of /etc/bind to bind:bind
  ansible.builtin.file:
    path: /etc/bind
    owner: bind
    group: bind
    recurse: true
  become: true

- name: Create logs directory for named
  ansible.builtin.file:
    path: /var/log/named
    state: directory
    owner: bind
    group: bind
    mode: "0755"

- name: Copy named.conf file
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: bind
    group: bind
    mode: "0660"
  notify: Restart named

- name: Create named directory
  ansible.builtin.file:
    path: /var/named
    state: directory
    owner: bind
    group: bind
    mode: "0755"

- name: Copy named.conf.local file
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: "0640"
  notify: Restart named

- name: Create zones directory
  ansible.builtin.file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: "0750"

- name: Copy forward zone file
  ansible.builtin.template:
    src: db.forward.j2
    dest: /etc/bind/zones/db.{{ setup_bind_domain }}
    owner: bind
    group: bind
    mode: "0640"
  notify: Restart named

- name: Copy reverse zone file
  ansible.builtin.template:
    src: db.reverse.j2
    dest: /etc/bind/zones/db.{{ setup_bind_rev_domain }}
    owner: bind
    group: bind
    mode: "0640"
  notify: Restart named
